name: CICD SmartPDF RAG

# Déclenchement automatique
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  lint-and-format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Nécessaire pour le push vers HF plus tard

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "latest"

      - name: Set up Python
        run: uv python install 3.11

      - name: Install Dependencies
        # On installe uniquement le groupe dev pour gagner du temps
        run: uv sync --group dev

      - name: Check Formatting (Black)
        # Échoue si le code n'est pas strictement formaté selon pyproject.toml
        run: uv run black . --check

      - name: Lint and Import Sorting (Ruff)
        # Échoue s'il y a des erreurs PEP8 ou des imports mal triés
        run: uv run ruff check .

      - name: Push to HF
        # S'exécute uniquement si le secret HF_TOKEN est configuré dans GitHub
        if: github.event_name == 'push' && success()
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          # Remplace 'ton-username' et 'ton-space-name' par tes vraies infos
          git remote add hf https://JulienSchnitzler:$HF_TOKEN@huggingface.co/spaces/JulienSchnitzler/SmartPDF_RAG
          git push --force hf HEAD:main